import { NoteModel, type NoteDocument } from "./note.model.js";
import { MemoryItemModel } from "../memory/memory.model.js";
import { ConceptNodeModel } from "../knowledge/concept.model.js";
import { ApiError } from "../../utils/api-error.js";
import { vectorSearchService } from "../../services/ai/vector-search.service.js";
import { studentIntelligenceService } from "../intelligence/student-intelligence.service.js";
import type { CareerNote } from "@studybuddy/shared";

type CreateNoteData = {
  title: string;
  content: string;
  topic?: string;
  tags?: string[];
  linkedSkills?: string[];
  sourceUrl?: string;
  strength?: number;
  nextReviewAt?: string;
  metadata?: Record<string, unknown>;
};

type UpdateNoteData = Partial<CreateNoteData>;

type LearningIngestionData = {
  text: string;
  source?: "cli" | "web" | "youtube" | "pdf" | "blog" | "github";
  sourceUrl?: string;
};

type NoteAnalysis = Awaited<ReturnType<typeof AIOrchestrator.analyzeNote>>;

type NotesQuery = {
  tags?: string;
  linkedSkills?: string;
  limit: number;
  offset: number;
};

export type ContradictionItem = {
  noteId: string;
  title: string;
  topic?: string;
  signals: string[];
  contentPreview: string;
  updatedAt: string;
};

import { usersService } from "../users/users.service.js";
import { AIOrchestrator } from "../../core/ai-orchestrator.js";
import { env } from "../../config/env.js";

const TECH_KEYWORDS = [
  "javascript", "typescript", "react", "node", "express", "mongodb", "docker", "kubernetes",
  "bfs", "dfs", "graph", "tree", "array", "hashmap", "recursion", "dynamic programming",
  "closure", "closures", "scope", "lexical scope", "useeffect", "hooks", "redux", "testing",
  "api", "database", "sql", "authentication", "authorization", "system design"
];

function titleFromLearningText(text: string) {
  return text
    .replace(/^(today\s+i\s+learned|i\s+learned|learned|studied|watched|read)\s+/i, "")
    .replace(/[.?!]+$/g, "")
    .trim()
    .slice(0, 80) || "Learning log";
}

function normalizeConceptName(value: string) {
  const trimmed = value.trim();
  if (!trimmed) return "";
  const aliases: Record<string, string> = {
    useeffect: "useEffect",
    closure: "Closures",
    closures: "Closures",
    bfs: "BFS traversal",
    dfs: "DFS traversal",
    hashmap: "Hash Map",
    api: "API"
  };
  return aliases[trimmed.toLowerCase()] ?? trimmed.replace(/\b\w/g, (c) => c.toUpperCase());
}

function inferTopicFromConcepts(concepts: string[], fallback: string) {
  const joined = `${concepts.join(" ")} ${fallback}`.toLowerCase();
  if (/(react|useeffect|hooks|redux)/.test(joined)) return "React";
  if (/(javascript|typescript|closure|scope)/.test(joined)) return "JavaScript";
  if (/(bfs|dfs|graph|tree|recursion|dynamic programming|array|hash)/.test(joined)) return "Data Structures and Algorithms";
  if (/(docker|kubernetes|container|image)/.test(joined)) return "DevOps";
  if (/(mongodb|database|sql)/.test(joined)) return "Databases";
  return fallback.slice(0, 48) || "General Learning";
}

function localAnalyzeLearning(title: string, content: string): NoteAnalysis {
  const text = `${title} ${content}`.toLowerCase();
  const concepts = Array.from(new Set(
    TECH_KEYWORDS
      .filter((keyword) => text.includes(keyword))
      .map(normalizeConceptName)
      .filter(Boolean)
  )).slice(0, 8);

  if (concepts.length === 0) {
    concepts.push(normalizeConceptName(title.split(/\s+/).slice(0, 3).join(" ")));
  }

  const topic = inferTopicFromConcepts(concepts, title);
  const isImplementation = /(bfs|dfs|algorithm|implement|code|docker|api|project|build)/i.test(content);
  const difficulty = /(advanced|system design|kubernetes|dynamic programming|optimization)/i.test(content)
    ? "advanced"
    : /(medium|hooks|useeffect|docker|graph|recursion|authentication)/i.test(content)
      ? "intermediate"
      : "beginner";

  return {
    topic,
    summary: content.slice(0, 220),
    concepts,
    difficulty,
    knowledgeLayer: isImplementation ? "application" : "understanding",
    conceptGraph: concepts.slice(1).map((concept) => ({
      from: concepts[0],
      to: concept,
      relationship: "related"
    })),
    executionTasks: [{
      title: isImplementation ? `Practice one small implementation using ${concepts[0]}` : `Explain ${concepts[0]} with one example`,
      type: isImplementation ? "code" : "explain",
      difficulty: difficulty === "advanced" ? "hard" : difficulty === "intermediate" ? "medium" : "easy"
    }],
    confusionSignals: detectContradictionPhrases(content),
    flashcards: concepts.slice(0, 4).map((concept) => ({
      question: `Explain ${concept} from memory.`,
      answer: `Review your note and describe the key idea, why it matters, and one example.`
    })),
    interviewRelevance: {
      frequency: isImplementation ? "high" : "medium",
      importance: isImplementation ? 70 : 45,
      usageContext: "Generated by local ingestion fallback until cloud analysis enriches it.",
      commonQuestions: concepts.slice(0, 3).map((concept) => `What is ${concept}, and when would you use it?`),
      realWorldUsage: [`Use ${concepts[0]} in a small practice task or project explanation.`]
    },
    revisionStrategy: isImplementation ? "implementation" : "conceptual",
    tags: Array.from(new Set([topic, ...concepts])).slice(0, 8)
  };
}

function detectContradictionPhrases(content: string) {
  const lower = content.toLowerCase();
  const signals: string[] = [];
  const pairs = [
    ["copy", "reference"],
    ["synchronous", "asynchronous"],
    ["mutable", "immutable"],
    ["stack", "heap"],
    ["client", "server"]
  ];

  for (const [left, right] of pairs) {
    if (lower.includes(left) && lower.includes(right)) {
      signals.push(`Potential contradiction or distinction to clarify: ${left} vs ${right}.`);
    }
  }

  return signals;
}

/** Converts a note document to the public API shape. */
function toNote(note: NoteDocument): CareerNote {
  return {
    id: String(note._id),
    userId: note.userId,
    title: note.title,
    content: note.content,
    topic: note.topic ?? undefined,
    tags: note.tags,
    linkedSkills: note.linkedSkills,
    sourceUrl: note.sourceUrl ?? undefined,
    sourceType: note.sourceType as any,
    strength: note.strength ?? 0,
    metadata: note.metadata,
    concepts: note.concepts || [],
    difficulty: (note.difficulty as any) || "beginner",
    knowledgeLayer: (note.knowledgeLayer as any) || "surface",
    interviewImportance: note.interviewImportance ?? 0,
    confusionCount: note.confusionCount ?? 0,
    revisionStrategy: (note.revisionStrategy as any) || "conceptual",
    relatedNoteIds: note.relatedNoteIds || [],
    projectLinks: note.projectLinks || [],
    nextReviewAt: note.nextReviewAt ? note.nextReviewAt.toISOString() : undefined,
    lastReviewed: note.lastReviewed ? note.lastReviewed.toISOString() : undefined,
    reviewCount: note.reviewCount ?? 0,
    lapseCount: note.lapseCount ?? 0,
    createdAt: note.createdAt.toISOString(),
    updatedAt: note.updatedAt.toISOString()
  };
}

/** Creates a new note for the user. */
async function createNote(userId: string, data: CreateNoteData): Promise<CareerNote> {
  const localAnalysis = localAnalyzeLearning(data.title, data.content);
  const note = await NoteModel.create({
    userId,
    title: data.title,
    content: data.content,
    topic: data.topic ?? data.tags?.[0] ?? localAnalysis.topic,
    tags: Array.from(new Set([...(data.tags ?? []), ...localAnalysis.tags])),
    linkedSkills: data.linkedSkills ?? [],
    sourceUrl: data.sourceUrl,
    strength: data.strength ?? 0.25,
    nextReviewAt: data.nextReviewAt ? new Date(data.nextReviewAt) : new Date(),
    metadata: {
      summary: localAnalysis.summary,
      concepts: localAnalysis.concepts,
      flashcards: localAnalysis.flashcards,
      retentionStrength: 25,
      difficulty: localAnalysis.difficulty,
      conceptGraph: localAnalysis.conceptGraph,
      executionTasks: localAnalysis.executionTasks,
      confusionSignals: localAnalysis.confusionSignals,
      knowledgeLayer: localAnalysis.knowledgeLayer,
      interviewRelevance: localAnalysis.interviewRelevance,
      analysisProvider: "local-fallback",
      ...(data.metadata ?? {})
    },
    concepts: localAnalysis.concepts,
    difficulty: localAnalysis.difficulty,
    knowledgeLayer: localAnalysis.knowledgeLayer,
    interviewImportance: localAnalysis.interviewRelevance.importance,
    revisionStrategy: localAnalysis.revisionStrategy
  });

  // Start AI analysis pipeline asynchronously
  runAnalysisPipeline(userId, note).catch(error =>
    console.error("AI Analysis Pipeline failed for note:", note._id, error)
  );

  // Generate embedding for the new note asynchronously
  vectorSearchService.updateNoteEmbedding(note._id.toString(), userId)
    .catch(error => console.error("Failed to generate embedding for new note:", error));

  // Initialize a MemoryItem for the note itself
  await MemoryItemModel.create({
    userId,
    noteId: note._id.toString(),
    content: note.content.substring(0, 150),
    nextReview: new Date(),
    strength: 0,
    interval: 1,
    repetitions: 0,
    easeFactor: 2.5
  }).catch(error => console.error("Failed to create MemoryItem for note:", error));

  studentIntelligenceService.emitEvent(userId, {
    type: "NOTE_CREATED",
    source: "notes",
    entityId: note._id.toString(),
    payload: { title: note.title, topic: note.topic, tags: note.tags, linkedSkills: note.linkedSkills }
  }).catch(error => console.error("Student intelligence event failed:", error));

  return toNote(note);
}

/** Captures natural-language learning without forcing the user to pre-categorize it. */
async function ingestLearning(userId: string, data: LearningIngestionData): Promise<CareerNote> {
  const title = titleFromLearningText(data.text);
  const localAnalysis = localAnalyzeLearning(title, data.text);

  return createNote(userId, {
    title,
    content: data.text,
    topic: localAnalysis.topic,
    tags: Array.from(new Set([data.source ?? "web", ...localAnalysis.tags])),
    sourceUrl: data.sourceUrl,
    strength: 0.2,
    nextReviewAt: new Date().toISOString()
  });
}

/**
 * Full AI analysis pipeline for a newly created note.
 * Extracts concepts, builds graph relationships, generates flashcards, and updates concept nodes.
 */
async function runAnalysisPipeline(userId: string, note: NoteDocument): Promise<void> {
  const profile = await usersService.getProfile(userId).catch(() => null);
  const userContext = profile ? `Target roles: ${profile.targetRoles?.join(", ")}` : "";

  let analysis: NoteAnalysis;
  let analysisProvider = env.geminiApiKey ? "gemini" : "groq";
  try {
    analysis = await AIOrchestrator.analyzeNote(note.title, note.content, userContext);
  } catch (error) {
    analysisProvider = "local-fallback";
    analysis = localAnalyzeLearning(note.title, note.content);
    console.warn("AI note analysis unavailable; using local extraction fallback:", error);
  }

  const currentNote = await NoteModel.findById(note._id).select("metadata").catch(() => null);
  const existingMetadata = ((currentNote?.metadata ?? note.metadata ?? {}) as Record<string, unknown>);
  const preservedCompanyPrep = existingMetadata.companyPrep;

  // Update note with enriched analysis data
  await NoteModel.updateOne(
    { _id: note._id },
    {
      $set: {
        metadata: {
          ...(preservedCompanyPrep ? { companyPrep: preservedCompanyPrep } : {}),
          summary: analysis.summary,
          concepts: analysis.concepts,
          flashcards: analysis.flashcards,
          retentionStrength: 25, // Initial
          difficulty: analysis.difficulty,
          conceptGraph: analysis.conceptGraph,
          executionTasks: analysis.executionTasks,
          confusionSignals: analysis.confusionSignals,
          knowledgeLayer: analysis.knowledgeLayer,
          interviewRelevance: analysis.interviewRelevance,
          analysisProvider
        },
        topic: analysis.topic,
        tags: [...new Set([...note.tags, ...analysis.tags])],
        concepts: analysis.concepts,
        difficulty: analysis.difficulty,
        knowledgeLayer: analysis.knowledgeLayer,
        interviewImportance: analysis.interviewRelevance.importance,
        revisionStrategy: analysis.revisionStrategy
      }
    }
  );

  // Initialize MemoryItems for flashcards
  if (analysis.flashcards && analysis.flashcards.length > 0) {
    await Promise.all(analysis.flashcards.map((card: any) =>
      MemoryItemModel.create({
        userId,
        noteId: note._id.toString(),
        content: `Q: ${card.question} | A: ${card.answer}`,
        nextReview: new Date(),
        strength: 0,
        interval: 1,
        repetitions: 0,
        easeFactor: 2.5
      })
    ));
  }

  // Upsert ConceptNodes and link to this note
  await upsertConceptNodes(userId, note._id.toString(), analysis);

  // Find and link related notes by shared concepts
  await linkRelatedNotes(userId, note._id.toString(), analysis.concepts);

  await studentIntelligenceService.emitEvent(userId, {
    type: "NOTE_UPDATED",
    source: "notes",
    entityId: note._id.toString(),
    payload: {
      title: note.title,
      concepts: analysis.concepts,
      difficulty: analysis.difficulty,
      knowledgeLayer: analysis.knowledgeLayer,
      interviewImportance: analysis.interviewRelevance.importance
    }
  }).catch(error => console.error("Student intelligence analysis event failed:", error));
}

/**
 * Creates or updates ConceptNode entries for extracted concepts.
 */
async function upsertConceptNodes(
  userId: string,
  noteId: string,
  analysis: Awaited<ReturnType<typeof AIOrchestrator.analyzeNote>>
): Promise<void> {
  const conceptIds: string[] = [];

  for (const conceptName of analysis.concepts) {
    try {
      const existing = await ConceptNodeModel.findOne({ userId, name: conceptName });

      if (existing) {
        // Add this note to the concept if not already linked
        if (!existing.noteIds.includes(noteId)) {
          existing.noteIds.push(noteId);
          await existing.save();
        }
        conceptIds.push(existing._id.toString());
      } else {
        // Determine category from concept graph relationships
        const category = inferConceptCategory(conceptName, analysis.topic);

        const newConcept = await ConceptNodeModel.create({
          userId,
          name: conceptName,
          category,
          difficulty: analysis.difficulty,
          noteIds: [noteId],
          interviewFrequency: analysis.interviewRelevance.frequency === "high" ? "high" : "medium"
        });
        conceptIds.push(newConcept._id.toString());
      }
    } catch (error) {
      // Duplicate key errors are fine — concept already exists
      if ((error as any)?.code !== 11000) {
        console.error(`Failed to upsert concept "${conceptName}":`, error);
      }
    }
  }

  // Link related concepts based on conceptGraph edges
  for (const edge of analysis.conceptGraph) {
    try {
      const fromConcept = await ConceptNodeModel.findOne({ userId, name: edge.from });
      const toConcept = await ConceptNodeModel.findOne({ userId, name: edge.to });

      if (fromConcept && toConcept) {
        const fromId = fromConcept._id.toString();
        const toId = toConcept._id.toString();

        if (!fromConcept.relatedConceptIds.includes(toId)) {
          fromConcept.relatedConceptIds.push(toId);
          await fromConcept.save();
        }
        if (!toConcept.relatedConceptIds.includes(fromId)) {
          toConcept.relatedConceptIds.push(fromId);
          await toConcept.save();
        }
      }
    } catch (error) {
      console.error("Failed to link concept edge:", edge, error);
    }
  }
}

/**
 * Infers concept category from the topic and concept name.
 */
function inferConceptCategory(
  conceptName: string,
  topic: string
): "algorithm" | "framework" | "pattern" | "language" | "concept" | "tool" {
  const lower = (conceptName + " " + topic).toLowerCase();

  const algoKeywords = ["algorithm", "sort", "search", "bfs", "dfs", "tree", "graph", "heap", "dynamic programming", "recursion", "traversal"];
  if (algoKeywords.some(k => lower.includes(k))) return "algorithm";

  const frameworkKeywords = ["react", "next", "vue", "angular", "express", "node", "django", "flask", "spring"];
  if (frameworkKeywords.some(k => lower.includes(k))) return "framework";

  const patternKeywords = ["pattern", "singleton", "observer", "factory", "decorator", "middleware", "mvc"];
  if (patternKeywords.some(k => lower.includes(k))) return "pattern";

  const langKeywords = ["javascript", "typescript", "python", "java", "c++", "rust", "go"];
  if (langKeywords.some(k => lower.includes(k))) return "language";

  const toolKeywords = ["git", "docker", "kubernetes", "webpack", "vite", "npm", "database", "sql", "mongodb", "redis"];
  if (toolKeywords.some(k => lower.includes(k))) return "tool";

  return "concept";
}

/**
 * Finds notes that share concepts and creates bidirectional links.
 */
async function linkRelatedNotes(
  userId: string,
  noteId: string,
  concepts: string[]
): Promise<void> {
  if (concepts.length === 0) return;

  // Find other notes that share any of these concepts
  const relatedNotes = await NoteModel.find({
    userId,
    _id: { $ne: noteId },
    concepts: { $in: concepts },
    deleted: { $ne: true }
  }).limit(10);

  const relatedIds = relatedNotes.map(n => n._id.toString());

  if (relatedIds.length > 0) {
    // Link this note to related notes
    await NoteModel.updateOne(
      { _id: noteId },
      { $addToSet: { relatedNoteIds: { $each: relatedIds } } }
    );

    // Link related notes back to this note
    await NoteModel.updateMany(
      { _id: { $in: relatedIds } },
      { $addToSet: { relatedNoteIds: noteId } }
    );
  }
}


/** Retrieves a single note by ID, ensuring it belongs to the user. */
async function getNote(userId: string, noteId: string): Promise<CareerNote> {
  const note = await NoteModel.findOne({ _id: noteId, userId });

  if (!note) {
    throw new ApiError(404, "Note not found.");
  }

  return toNote(note);
}

/** Updates an existing note, ensuring it belongs to the user. */
async function updateNote(userId: string, noteId: string, data: UpdateNoteData): Promise<CareerNote> {
  const note = await NoteModel.findOneAndUpdate(
    { _id: noteId, userId },
    {
      ...(data.title !== undefined && { title: data.title }),
      ...(data.content !== undefined && { content: data.content }),
      ...(data.topic !== undefined && { topic: data.topic }),
      ...(data.tags !== undefined && { tags: data.tags }),
      ...(data.linkedSkills !== undefined && { linkedSkills: data.linkedSkills }),
      ...(data.sourceUrl !== undefined && { sourceUrl: data.sourceUrl }),
      ...(data.strength !== undefined && { strength: data.strength }),
      ...(data.nextReviewAt !== undefined && { nextReviewAt: new Date(data.nextReviewAt) })
    },
    { new: true, runValidators: true }
  );

  if (!note) {
    throw new ApiError(404, "Note not found.");
  }

  // Re-run AI analysis if content or title changed
  if (data.title !== undefined || data.content !== undefined) {
    vectorSearchService.updateNoteEmbedding(noteId, userId)
      .catch(error => console.error("Failed to update embedding for modified note:", error));

    // Re-analyze in background
    runAnalysisPipeline(userId, note).catch(error =>
      console.error("Re-analysis pipeline failed:", error)
    );
  }

  studentIntelligenceService.emitEvent(userId, {
    type: "NOTE_UPDATED",
    source: "notes",
    entityId: noteId,
    payload: { changedFields: Object.keys(data), title: note.title, topic: note.topic }
  }).catch(error => console.error("Student intelligence event failed:", error));

  return toNote(note);
}

/** Deletes a note, ensuring it belongs to the user. */
async function deleteNote(userId: string, noteId: string): Promise<void> {
  const result = await NoteModel.deleteOne({ _id: noteId, userId });

  if (result.deletedCount === 0) {
    throw new ApiError(404, "Note not found.");
  }

  // Clean up related data
  await MemoryItemModel.deleteMany({ userId, noteId }).catch(() => {});

  // Remove this note from concept nodes
  await ConceptNodeModel.updateMany(
    { userId, noteIds: noteId },
    { $pull: { noteIds: noteId } }
  ).catch(() => {});

  // Remove from related notes
  await NoteModel.updateMany(
    { userId, relatedNoteIds: noteId },
    { $pull: { relatedNoteIds: noteId } }
  ).catch(() => {});

  studentIntelligenceService.emitEvent(userId, {
    type: "NOTE_DELETED",
    source: "notes",
    entityId: noteId
  }).catch(error => console.error("Student intelligence event failed:", error));
}

async function listContradictions(userId: string): Promise<ContradictionItem[]> {
  const notes = await NoteModel.find({
    userId,
    deleted: { $ne: true },
    "metadata.confusionSignals.0": { $exists: true }
  }).sort({ updatedAt: -1 }).limit(50);

  return notes.map((note) => ({
    noteId: String(note._id),
    title: note.title,
    topic: note.topic ?? undefined,
    signals: ((note.metadata as any)?.confusionSignals ?? []).map(String),
    contentPreview: note.content.slice(0, 220),
    updatedAt: note.updatedAt.toISOString()
  }));
}

async function resolveContradiction(userId: string, noteId: string, resolutionNote?: string): Promise<CareerNote> {
  const note = await NoteModel.findOne({ _id: noteId, userId, deleted: { $ne: true } });
  if (!note) {
    throw new ApiError(404, "Note not found.");
  }

  const metadata = { ...((note.metadata as any) ?? {}) };
  const oldSignals = Array.isArray(metadata.confusionSignals) ? metadata.confusionSignals : [];
  metadata.resolvedContradictions = [
    ...(Array.isArray(metadata.resolvedContradictions) ? metadata.resolvedContradictions : []),
    {
      signals: oldSignals,
      resolutionNote: resolutionNote?.trim() || "Marked clarified by user.",
      resolvedAt: new Date().toISOString()
    }
  ];
  metadata.confusionSignals = [];

  note.metadata = metadata;
  note.evolutionHistory = [
    ...(note.evolutionHistory ?? []),
    {
      type: "contradiction_resolved",
      signals: oldSignals,
      note: resolutionNote?.trim(),
      at: new Date().toISOString()
    }
  ];
  await note.save();

  return toNote(note);
}

/** Lists notes for the user with optional filtering. */
async function listNotes(userId: string, query: NotesQuery): Promise<{ notes: CareerNote[]; total: number }> {
  const filter: any = { userId, deleted: { $ne: true } };

  if (query.tags) {
    filter.tags = { $in: query.tags.split(",").map(tag => tag.trim()) };
  }

  if (query.linkedSkills) {
    filter.linkedSkills = { $in: query.linkedSkills.split(",").map(skill => skill.trim()) };
  }

  const total = await NoteModel.countDocuments(filter);
  const notes = await NoteModel.find(filter)
    .sort({ updatedAt: -1 })
    .skip(query.offset)
    .limit(query.limit);

  return {
    notes: notes.map(toNote),
    total
  };
}

export const notesService = {
  createNote,
  ingestLearning,
  getNote,
  updateNote,
  deleteNote,
  listContradictions,
  resolveContradiction,
  listNotes,
  searchNotes: vectorSearchService.searchNotes,
  updateAllNoteEmbeddings: vectorSearchService.updateAllNoteEmbeddings,
  getNotesContextForQuery: vectorSearchService.getNotesContextForQuery
};

export const __notesTestUtils = {
  titleFromLearningText,
  localAnalyzeLearning,
  detectContradictionPhrases
};
