import { Link } from "react-router-dom";
import {
  ArrowRight,
  BrainCircuit,
  MessageSquare,
  Route,
  Sparkles,
  Target,
  Layers,
  Network,
  Cpu,
  Github,
  Linkedin,
  MessageCircle,
  CircleHelp
} from "lucide-react";
import { useAppStore } from "../store/app-store";
import { motion } from "framer-motion";

const features = [
  {
    icon: Target,
    title: "AI Skill Gap Analysis",
    text: "Identify exactly what you're missing for your dream role using our deep-learning engine.",
  },
  {
    icon: Route,
    title: "Dynamic Roadmaps",
    text: "Convert your skill gaps into actionable, weekly milestones that adapt to your pace.",
  },
  {
    icon: MessageSquare,
    title: "Veda AI",
    text: "An AI that remembers your notes, resume, and job applications for hyper-personalized advice.",
  },
  {
    icon: Layers,
    title: "Project Forge",
    text: "Build portfolio-worthy projects with AI guidance tailored to your learning path.",
  }
];

const howToUseSteps = [
  {
    title: "Sync your notes",
    text: "Run the local C++ agent to securely sync your markdown notes, resumes, and study materials into the platform."
  },
  {
    title: "Identify your gap",
    text: "Select a target role. StudyBuddy analyzes your synced notes to find what skills you already have, and what you're missing."
  },
  {
    title: "Follow the roadmap",
    text: "Get a personalized week-by-week study plan generated by AI to bridge the gap and land the job."
  }
];

const trustItems = [
  "Built for tech careers",
  "Offline-first C++ CLI Sync",
  "Semantic skill matching",
  "RAG-powered Veda AI",
];

export function LandingPage() {
  const isAuthenticated = useAppStore((state) => state.isAuthenticated);

  return (
    <div className="min-h-screen bg-obsidian text-slate-300 font-sans overflow-x-hidden selection:bg-brand/30 selection:text-white">
      {/* Background Gradients */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-brand/10 blur-[120px] rounded-full mix-blend-screen" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] bg-cyan/10 blur-[120px] rounded-full mix-blend-screen" />
        <div className="absolute inset-0 bg-grid opacity-[0.03]" />
      </div>

      <main className="relative z-10 max-w-7xl mx-auto px-6 py-12 md:py-24">
        
        {/* HERO SECTION */}
        <section className="grid lg:grid-cols-[1.1fr_0.9fr] gap-16 lg:gap-8 items-center min-h-[calc(100vh-12rem)]">
          <div className="space-y-8">
            <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-brand/20 bg-brand/10 text-brand font-semibold text-xs tracking-widest uppercase">
              <Sparkles size={16} />
              Career prep, guided by AI
            </span>
            
            <h1 className="text-5xl md:text-7xl font-black text-white leading-[1.1] tracking-tight">
              Plan your next <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand to-cyan">big move</span> with precision.
            </h1>
            
            <p className="text-lg md:text-xl leading-relaxed text-slate-400 max-w-2xl">
              StudyBuddy brings your notes, resumes, and study plans into one connected AI system that helps you close the skill gap and land your target role.
            </p>

            <div className="flex flex-wrap items-center gap-4 pt-4">
              <Link
                to={isAuthenticated ? "/dashboard" : "/auth"}
                className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-full bg-white text-obsidian font-bold text-lg hover:scale-105 transition-all shadow-[0_0_40px_rgba(255,255,255,0.15)]"
              >
                Get Started
                <ArrowRight size={20} />
              </Link>
              <a href="#features" className="inline-flex items-center justify-center px-8 py-4 rounded-full border border-white/10 hover:bg-white/5 font-medium text-white transition-colors">
                Explore Features
              </a>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-8">
              <div className="p-5 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-md">
                <strong className="block text-2xl font-bold text-white">24/7</strong>
                <span className="text-sm text-slate-400 mt-1">Veda AI Guidance</span>
              </div>
              <div className="p-5 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-md">
                <strong className="block text-2xl font-bold text-white">1 tool</strong>
                <span className="text-sm text-slate-400 mt-1">Notes to Roadmap flow</span>
              </div>
              <div className="p-5 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-md">
                <strong className="block text-2xl font-bold text-white">Offline</strong>
                <span className="text-sm text-slate-400 mt-1">C++ Agent syncing</span>
              </div>
            </div>
          </div>

          <div className="relative h-[500px] w-full rounded-3xl border border-white/10 bg-gradient-to-b from-brand/10 to-transparent shadow-2xl overflow-hidden flex items-center justify-center">
            {/* Orbits */}
            <div className="absolute w-[400px] h-[400px] rounded-full border border-white/10" />
            <div className="absolute w-[280px] h-[280px] rounded-full border border-white/10 border-dashed animate-spin-slow" style={{ animationDuration: '40s' }} />
            
            {/* Center Node (Live AI State) */}
            <div className="absolute flex items-center justify-center">
              {/* Idle / Background Glow */}
              <motion.div 
                animate={{ 
                  scale: [1, 1.2, 1],
                  opacity: [0.3, 0.5, 0.3]
                }}
                transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                className="absolute w-32 h-32 bg-brand/30 rounded-full blur-3xl" 
              />
              
              {/* Processing Particles (Conditional) */}
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 10, repeat: Infinity, ease: "linear" }}
                className="absolute w-40 h-40"
              >
                {[...Array(6)].map((_, i) => (
                  <motion.div
                    key={i}
                    animate={{ 
                      scale: [0, 1, 0],
                      opacity: [0, 0.8, 0],
                      x: [0, (i % 2 === 0 ? 40 : -40)],
                      y: [0, (i < 3 ? 40 : -40)]
                    }}
                    transition={{ 
                      duration: 3, 
                      repeat: Infinity, 
                      delay: i * 0.5,
                      ease: "easeInOut" 
                    }}
                    className="absolute w-1.5 h-1.5 bg-cyan rounded-full"
                    style={{ 
                      left: '50%', 
                      top: '50%',
                      marginLeft: '-3px',
                      marginTop: '-3px'
                    }}
                  />
                ))}
              </motion.div>

              {/* Core Hub */}
              <motion.div 
                animate={{ 
                  scale: [1, 1.1, 1.25, 1],
                  boxShadow: [
                    "0 0 20px rgba(139, 92, 246, 0.3)", 
                    "0 0 40px rgba(139, 92, 246, 0.6)",
                    "0 0 80px rgba(255, 255, 255, 0.8)",
                    "0 0 20px rgba(139, 92, 246, 0.3)"
                  ]
                }}
                transition={{ 
                  duration: 6, 
                  repeat: Infinity, 
                  times: [0, 0.4, 0.45, 0.6], // Pulse -> Flash -> Settle
                  ease: "easeInOut" 
                }}
                className="relative w-14 h-14 bg-white rounded-full shadow-xl flex items-center justify-center z-10"
              >
                <Cpu className="text-brand" size={24} />
              </motion.div>
            </div>

            {/* Clusters */}
            <motion.div 
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: [0, -12, 0], opacity: 1 }}
              transition={{ 
                opacity: { delay: 0.5, duration: 0.8 },
                y: { delay: 1.3, duration: 5, repeat: Infinity, ease: "easeInOut" }
              }}
              className="absolute top-[15%] left-[5%] p-4 rounded-xl border border-white/10 bg-black/60 backdrop-blur-md w-64 shadow-xl"
            >
              <div className="flex items-center gap-2 text-cyan font-semibold text-xs uppercase tracking-wider mb-2">
                <Network size={14} /> Local Agent
              </div>
              <strong className="text-white text-lg leading-tight block">3 notes synced</strong>
              <span className="text-slate-400 text-sm mt-1 block">Ready for RAG indexing</span>
            </motion.div>

            <motion.div 
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: [0, 12, 0], opacity: 1 }}
              transition={{ 
                opacity: { delay: 0.7, duration: 0.8 },
                y: { delay: 1.5, duration: 4.5, repeat: Infinity, ease: "easeInOut" }
              }}
              className="absolute bottom-[20%] right-[5%] p-4 rounded-xl border border-white/10 bg-black/60 backdrop-blur-md shadow-xl"
            >
              <div className="flex items-center gap-2 text-brand font-semibold text-xs uppercase tracking-wider mb-2">
                <BrainCircuit size={14} /> Veda Active
              </div>
              <span className="text-slate-300 text-sm block">I've analyzed your notes. You're 85% ready for that Frontend role—let's bridge the gap.</span>
            </motion.div>

          </div>
        </section>

        {/* TRUST BAR */}
        <section className="flex flex-wrap justify-center gap-4 py-12 mt-12 border-y border-white/5">
          {trustItems.map((item) => (
            <div key={item} className="flex items-center gap-3 px-6 py-3 rounded-full border border-white/10 bg-white/5 backdrop-blur-sm text-sm font-medium text-slate-300 shadow-inner shadow-white/5">
              <div className="w-2 h-2 rounded-full bg-gradient-to-br from-brand to-cyan shadow-[0_0_10px_var(--color-brand)]" />
              {item}
            </div>
          ))}
        </section>

        {/* FEATURES GRID */}
        <section id="features" className="py-24 md:py-32">
          <div className="max-w-2xl">
            <span className="text-xs font-bold uppercase tracking-[0.2em] text-brand mb-4 block">Why it works</span>
            <h2 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-6">Built for actual career growth, not just generic advice.</h2>
            <p className="text-lg text-slate-400">
              Every feature is designed to reduce the noise, pinpoint your weaknesses, and provide highly-contextual steps to reach your goal.
            </p>
          </div>

          <motion.div 
            className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mt-16"
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6, staggerChildren: 0.15 }}
          >
            {features.map((feature, i) => (
              <motion.article 
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="p-8 rounded-3xl border border-white/10 bg-white/5 hover:bg-white/10 transition-colors group"
              >
                <div className="w-12 h-12 rounded-xl bg-brand/20 text-brand flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <feature.icon size={24} />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">{feature.title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{feature.text}</p>
              </motion.article>
            ))}
          </motion.div>
        </section>

        {/* HOW TO USE */}
        <section className="py-24 md:py-32 border-t border-white/5">
          <div className="max-w-2xl mb-16">
            <span className="text-xs font-bold uppercase tracking-[0.2em] text-cyan mb-4 block">How to use</span>
            <h2 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-6">A simple workflow to master any role.</h2>
            <p className="text-lg text-slate-400">
              StudyBuddy works best when you keep your notes synced via the local CLI, set your target role, and let the AI build the bridge.
            </p>
          </div>

          <motion.div 
            className="grid md:grid-cols-3 gap-6"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
          >
            {howToUseSteps.map((step, i) => (
              <motion.article 
                key={step.title}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="p-8 rounded-3xl border border-white/10 bg-gradient-to-b from-white/5 to-transparent relative overflow-hidden group hover:border-white/20 transition-all"
              >
                <span className="inline-block px-3 py-1 rounded-full bg-cyan/20 text-cyan text-xs font-bold uppercase tracking-wider mb-6">
                  Step {i + 1}
                </span>
                <h3 className="text-2xl font-bold text-white mb-4">{step.title}</h3>
                <p className="text-slate-400 leading-relaxed">{step.text}</p>
              </motion.article>
            ))}
          </motion.div>

          <div className="mt-12 p-6 rounded-2xl border border-brand/20 bg-brand/5 flex items-start gap-4 text-slate-300">
            <CircleHelp className="text-brand flex-shrink-0 mt-0.5" size={20} />
            <span className="text-sm leading-relaxed">
              <strong>Pro tip:</strong> Write your notes in Markdown locally using Obsidian or VS Code. The C++ Agent runs silently in the background, pushing changes to the cloud so Veda AI always has your latest context.
            </span>
          </div>
        </section>

        {/* CTA SECTION */}
        <section className="py-16 md:py-20 px-8 md:px-16 rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-brand/20 via-obsidian to-cyan/20 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-10 shadow-2xl">
          <div className="absolute inset-0 bg-grid opacity-[0.05]" />
          <div className="relative z-10 max-w-xl">
            <span className="text-xs font-bold uppercase tracking-[0.2em] text-white/50 mb-4 block">Built for developers</span>
            <h2 className="text-3xl md:text-4xl font-bold text-white leading-tight mb-4">Ready to turn learning chaos into a clear roadmap?</h2>
            <p className="text-slate-300 text-lg">
              Start with your notes, add your target role, and let AI guide your next project.
            </p>
          </div>
          <Link
            to="/auth"
            className="relative z-10 whitespace-nowrap px-8 py-4 rounded-full bg-white text-obsidian font-bold text-lg hover:scale-105 transition-transform shadow-[0_0_30px_rgba(255,255,255,0.2)]"
          >
            Launch StudyBuddy
          </Link>
        </section>

      </main>

      {/* FOOTER */}
      <footer className="border-t border-white/5 mt-32">
        <div className="max-w-7xl mx-auto px-6 py-12 grid md:grid-cols-[1.5fr_1fr_1fr] gap-10">
          <div>
            <strong className="text-xl font-bold text-white flex items-center gap-2 mb-4">
              <div className="w-8 h-8 rounded-lg bg-brand flex items-center justify-center text-obsidian text-sm">SB</div>
              StudyBuddy
            </strong>
            <p className="text-slate-400 text-sm max-w-xs leading-relaxed">
              Your AI Career Mentor. Notes, roadmaps, and intelligent guidance in one connected system.
            </p>
          </div>
          
          <div className="flex flex-col gap-3">
            <strong className="text-white mb-2">Platform</strong>
            <Link to="/" className="text-slate-400 hover:text-white transition-colors text-sm">Home</Link>
            <a href="#features" className="text-slate-400 hover:text-white transition-colors text-sm">Features</a>
            <Link to="/auth" className="text-slate-400 hover:text-white transition-colors text-sm">Login</Link>
          </div>

          <div className="flex flex-col gap-3">
            <strong className="text-white mb-2">Connect</strong>
            <a href="#" className="text-slate-400 hover:text-white transition-colors text-sm flex items-center gap-2">
              <Github size={16} /> GitHub
            </a>
            <a href="https://www.linkedin.com/in/priyanshu-tiwari-pds37" target="_blank" rel="noopener noreferrer" className="text-slate-400 hover:text-white transition-colors text-sm flex items-center gap-2">
              <Linkedin size={16} /> LinkedIn
            </a>
            <a href="#" className="text-slate-400 hover:text-white transition-colors text-sm flex items-center gap-2">
              <MessageCircle size={16} /> Discord
            </a>
          </div>
        </div>
        
        <div className="max-w-7xl mx-auto px-6 py-6 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <span>&copy; {new Date().getFullYear()} StudyBuddy AI. All rights reserved.</span>
          <div className="flex gap-4">
            <Link to="/privacy" className="hover:text-slate-300">Privacy Policy</Link>
            <Link to="/terms" className="hover:text-slate-300">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
